name: Deploy infrastructure using Terraform
on:
  workflow_dispatch:
    inputs:
      id:
        type: string
        required: false
      action:
        type: choice
        required: true
        options: 
        - apply
        - destroy
permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: "terraform"
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
  deploy:
    name: Terraform init and apply or destroy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::905418258334:role/GithubAccess
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform ${{ inputs.action }} 